/*
 * Copyright 2017 jurgen.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.messfuchs.geo.gui;

import com.messfuchs.geo.models.BEVMerger;

/**
 *
 * @author jurgen
 */
public class BEVMergerUI extends javax.swing.JFrame {

    /**
     * Creates new form BEVPairUI
     */
    public BEVMergerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcInMGI = new javax.swing.JFileChooser();
        fcInETRS = new javax.swing.JFileChooser();
        fcOutMerged = new javax.swing.JFileChooser();
        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        txtInMGI = new javax.swing.JTextField();
        btnInMGI = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtInETRS = new javax.swing.JTextField();
        btnInETRS = new javax.swing.JButton();
        btnMerge = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtOutMerged = new javax.swing.JTextField();
        btnOutMerged = new javax.swing.JButton();

        fcInMGI.setDialogTitle("BEV In MGI");
        fcInMGI.setToolTipText("Choose BEV File containing MGI data");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BEV MGI File:");

        txtInMGI.setText("/home/jurgen/Documents/Arbeit/Landmark/Kunden/Fankhauser/20170824-Trafo/identpunkte/0004769401_200_PUNKTART_EP.csv");

        btnInMGI.setText("...");
        btnInMGI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInMGIActionPerformed(evt);
            }
        });

        jLabel2.setText("BEV ETRS File:");

        txtInETRS.setText("/home/jurgen/Documents/Arbeit/Landmark/Kunden/Fankhauser/20170824-Trafo/identpunkte/0004769401_100_PUNKTART_EP.csv");
        txtInETRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInETRSActionPerformed(evt);
            }
        });

        btnInETRS.setText("...");
        btnInETRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInETRSActionPerformed(evt);
            }
        });

        btnMerge.setText("Merge");
        btnMerge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMergeActionPerformed(evt);
            }
        });

        jLabel3.setText("OUT File:");

        txtOutMerged.setText("/home/jurgen/Documents/Arbeit/Landmark/Kunden/Fankhauser/20170824-Trafo/identpunkte/0004769401_PUNKTART_EP_TEST.csv");
        txtOutMerged.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutMergedActionPerformed(evt);
            }
        });

        btnOutMerged.setText("jButton4");
        btnOutMerged.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutMergedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMerge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtInMGI))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtInETRS)
                                    .addComponent(txtOutMerged))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnInMGI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInETRS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOutMerged, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtInMGI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInMGI))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtInETRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInETRS))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtOutMerged, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOutMerged))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnMerge)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInETRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInETRSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInETRSActionPerformed

    private void txtOutMergedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutMergedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOutMergedActionPerformed

    private void btnMergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMergeActionPerformed
        // TODO add your handling code here:
        
        BEVMerger merger = new BEVMerger(
                this.txtInMGI.getText(), 
                this.txtInETRS.getText(),
                this.txtOutMerged.getText()
        );
        
        try {
            merger.convert();
        } catch (java.io.IOException e)  {
            e.printStackTrace();
            System.out.println("There was an Error");
        }
    }//GEN-LAST:event_btnMergeActionPerformed

    private void btnInMGIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInMGIActionPerformed
        // TODO add your handling code here:
        int returnVal = this.jFileChooser1.showOpenDialog(this);
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = this.jFileChooser1.getSelectedFile();
            this.txtInMGI.setText(file.getAbsolutePath());
        
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_btnInMGIActionPerformed

    private void btnInETRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInETRSActionPerformed
        // TODO add your handling code here:
        int returnVal = this.jFileChooser1.showOpenDialog(this);
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = this.jFileChooser1.getSelectedFile();
            this.txtInETRS.setText(file.getAbsolutePath());
        
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_btnInETRSActionPerformed

    private void btnOutMergedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutMergedActionPerformed
        // TODO add your handling code here:
        int returnVal = this.jFileChooser1.showOpenDialog(this);
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = this.jFileChooser1.getSelectedFile();
            this.txtOutMerged.setText(file.getAbsolutePath());
        } else {
            System.out.println("File access cancelled by user.");
        }         
    }//GEN-LAST:event_btnOutMergedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BEVMergerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BEVMergerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BEVMergerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BEVMergerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BEVMergerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInETRS;
    private javax.swing.JButton btnInMGI;
    private javax.swing.JButton btnMerge;
    private javax.swing.JButton btnOutMerged;
    private javax.swing.JFileChooser fcInETRS;
    private javax.swing.JFileChooser fcInMGI;
    private javax.swing.JFileChooser fcOutMerged;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtInETRS;
    private javax.swing.JTextField txtInMGI;
    private javax.swing.JTextField txtOutMerged;
    // End of variables declaration//GEN-END:variables
}
