/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.messfuchs.geo.gui;

/**
 *
 * @author jurgen
 */
public class TricotUI extends javax.swing.JFrame {
    
    final javax.swing.JFileChooser inputFileChooser;
    public String inputFormat;
    public String outputFormat;

    /**
     * Creates new form TricotUI
     */
    public TricotUI() {
        initComponents();
        this.inputFileChooser = new javax.swing.JFileChooser();
        inputFormat = "GSI";
        outputFormat = "GSI";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        statusLabel = new javax.swing.JLabel();
        convertButton = new javax.swing.JButton();
        controlPanel = new javax.swing.JPanel();
        configTabbedPane = new javax.swing.JTabbedPane();
        inputConfigPanel = new javax.swing.JPanel();
        inputFormatComboBox = new javax.swing.JComboBox<>();
        inputMainPanel1 = new javax.swing.JPanel();
        gsiInputPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        gsiInButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        siteIndicatorTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        stationIndicatorTextField1 = new javax.swing.JTextField();
        gsiInputTextField1 = new javax.swing.JTextField();
        csvInputPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        rmgInputPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        outputConfigPanel = new javax.swing.JPanel();
        outputFormatComboBox = new javax.swing.JComboBox<>();
        outputMainPanel1 = new javax.swing.JPanel();
        gsiOutputPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        gsiOutButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        siteIndicatorOutTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        stationIndicatorOutTextField1 = new javax.swing.JTextField();
        gsiOutputTextField1 = new javax.swing.JTextField();
        csvOutputPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        rmgOutputPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tricot UI");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        statusLabel.setText("TachymetRIic COnverter Tool");
        statusLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        statusLabel.setName("statusLabel"); // NOI18N

        convertButton.setText("Convert");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        configTabbedPane.setPreferredSize(new java.awt.Dimension(1000, 400));

        inputConfigPanel.setPreferredSize(new java.awt.Dimension(987, 400));

        inputFormatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GSI", "CSV", "RMGeo" }));
        inputFormatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFormatComboBoxActionPerformed(evt);
            }
        });

        inputMainPanel1.setName("Input Panel"); // NOI18N
        inputMainPanel1.setPreferredSize(new java.awt.Dimension(685, 373));
        inputMainPanel1.setLayout(new java.awt.CardLayout(5, 5));

        jLabel9.setText("GSI File");

        gsiInButton1.setText("...");
        gsiInButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gsiInButton1ActionPerformed(evt);
            }
        });

        jLabel10.setText("SiteIndicator");
        jLabel10.setPreferredSize(new java.awt.Dimension(120, 17));

        siteIndicatorTextField1.setText("1");

        jLabel11.setText("StationIndicator");

        stationIndicatorTextField1.setText("11");
        stationIndicatorTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stationIndicatorTextField1ActionPerformed(evt);
            }
        });

        gsiInputTextField1.setText("INPUT.GSI");

        javax.swing.GroupLayout gsiInputPanel1Layout = new javax.swing.GroupLayout(gsiInputPanel1);
        gsiInputPanel1.setLayout(gsiInputPanel1Layout);
        gsiInputPanel1Layout.setHorizontalGroup(
            gsiInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gsiInputPanel1Layout.createSequentialGroup()
                .addGroup(gsiInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gsiInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(gsiInputPanel1Layout.createSequentialGroup()
                        .addComponent(gsiInputTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(gsiInButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(siteIndicatorTextField1)
                    .addComponent(stationIndicatorTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        gsiInputPanel1Layout.setVerticalGroup(
            gsiInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gsiInputPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(gsiInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(gsiInButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gsiInputTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(gsiInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siteIndicatorTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(gsiInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stationIndicatorTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputMainPanel1.add(gsiInputPanel1, "GSI");

        jLabel17.setText("CSV INPUT CONFIGURAION");

        javax.swing.GroupLayout csvInputPanel1Layout = new javax.swing.GroupLayout(csvInputPanel1);
        csvInputPanel1.setLayout(csvInputPanel1Layout);
        csvInputPanel1Layout.setHorizontalGroup(
            csvInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(csvInputPanel1Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        csvInputPanel1Layout.setVerticalGroup(
            csvInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(csvInputPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputMainPanel1.add(csvInputPanel1, "CSV");

        jLabel18.setText("RMGEO INPUT CONFIGURAION");

        javax.swing.GroupLayout rmgInputPanel1Layout = new javax.swing.GroupLayout(rmgInputPanel1);
        rmgInputPanel1.setLayout(rmgInputPanel1Layout);
        rmgInputPanel1Layout.setHorizontalGroup(
            rmgInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rmgInputPanel1Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rmgInputPanel1Layout.setVerticalGroup(
            rmgInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rmgInputPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputMainPanel1.add(rmgInputPanel1, "RMGeo");

        javax.swing.GroupLayout inputConfigPanelLayout = new javax.swing.GroupLayout(inputConfigPanel);
        inputConfigPanel.setLayout(inputConfigPanelLayout);
        inputConfigPanelLayout.setHorizontalGroup(
            inputConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputConfigPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputMainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
                    .addComponent(inputFormatComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        inputConfigPanelLayout.setVerticalGroup(
            inputConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputConfigPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputFormatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputMainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        configTabbedPane.addTab("Input Configuration", inputConfigPanel);

        outputConfigPanel.setPreferredSize(new java.awt.Dimension(987, 400));

        outputFormatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GSI", "CSV", "RMGeo" }));
        outputFormatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputFormatComboBoxActionPerformed(evt);
            }
        });

        outputMainPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        outputMainPanel1.setName("Output Panel"); // NOI18N
        outputMainPanel1.setLayout(new java.awt.CardLayout());

        jLabel12.setText("GSI File");

        gsiOutButton1.setText("...");
        gsiOutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gsiOutButton1ActionPerformed(evt);
            }
        });

        jLabel13.setText("SiteIndicator");

        siteIndicatorOutTextField1.setText("1");

        jLabel14.setText("StationIndicator");

        stationIndicatorOutTextField1.setText("11");
        stationIndicatorOutTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stationIndicatorOutTextField1ActionPerformed(evt);
            }
        });

        gsiOutputTextField1.setText("OUTPUT.GSI");

        javax.swing.GroupLayout gsiOutputPanel1Layout = new javax.swing.GroupLayout(gsiOutputPanel1);
        gsiOutputPanel1.setLayout(gsiOutputPanel1Layout);
        gsiOutputPanel1Layout.setHorizontalGroup(
            gsiOutputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gsiOutputPanel1Layout.createSequentialGroup()
                .addGroup(gsiOutputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(gsiOutputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(siteIndicatorOutTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gsiOutputPanel1Layout.createSequentialGroup()
                        .addComponent(gsiOutputTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gsiOutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(stationIndicatorOutTextField1))
                .addContainerGap())
        );
        gsiOutputPanel1Layout.setVerticalGroup(
            gsiOutputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gsiOutputPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(gsiOutputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(gsiOutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gsiOutputTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(gsiOutputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siteIndicatorOutTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(gsiOutputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stationIndicatorOutTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        outputMainPanel1.add(gsiOutputPanel1, "GSI");

        jLabel16.setText("CSV OUTPUT CONFIGURATION");

        javax.swing.GroupLayout csvOutputPanel1Layout = new javax.swing.GroupLayout(csvOutputPanel1);
        csvOutputPanel1.setLayout(csvOutputPanel1Layout);
        csvOutputPanel1Layout.setHorizontalGroup(
            csvOutputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16)
        );
        csvOutputPanel1Layout.setVerticalGroup(
            csvOutputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, csvOutputPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        outputMainPanel1.add(csvOutputPanel1, "CSV");

        jLabel15.setText("RMGeo OUTPUT CONFIGURATION");

        javax.swing.GroupLayout rmgOutputPanel1Layout = new javax.swing.GroupLayout(rmgOutputPanel1);
        rmgOutputPanel1.setLayout(rmgOutputPanel1Layout);
        rmgOutputPanel1Layout.setHorizontalGroup(
            rmgOutputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15)
        );
        rmgOutputPanel1Layout.setVerticalGroup(
            rmgOutputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rmgOutputPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        outputMainPanel1.add(rmgOutputPanel1, "RMGeo");

        javax.swing.GroupLayout outputConfigPanelLayout = new javax.swing.GroupLayout(outputConfigPanel);
        outputConfigPanel.setLayout(outputConfigPanelLayout);
        outputConfigPanelLayout.setHorizontalGroup(
            outputConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outputConfigPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(outputConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outputMainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
                    .addComponent(outputFormatComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        outputConfigPanelLayout.setVerticalGroup(
            outputConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputConfigPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outputFormatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outputMainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        configTabbedPane.addTab("Output Configuration", outputConfigPanel);

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addComponent(configTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addComponent(configTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 274, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statusLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(convertButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(convertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        // TODO add your handling code here:
        java.lang.StringBuilder s = new java.lang.StringBuilder();
        s.append("Converting ");
        s.append(this.inputFormat);
        s.append(" to ");
        s.append(this.outputFormat);
        this.statusLabel.setText(s.toString());
    }//GEN-LAST:event_convertButtonActionPerformed

    private void outputFormatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputFormatComboBoxActionPerformed
        // TODO add your handling code here:
        if (this.outputFormatComboBox.getSelectedIndex() != -1) {
            this.outputFormat = (String)this.outputFormatComboBox.getItemAt(this.outputFormatComboBox.getSelectedIndex());
            java.awt.CardLayout cardLayout = (java.awt.CardLayout)(outputMainPanel1.getLayout());
            cardLayout.show(outputMainPanel1, this.outputFormat);
        }
        statusLabel.setText("Output Format set to " + this.outputFormat);
    }//GEN-LAST:event_outputFormatComboBoxActionPerformed

    private void inputFormatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFormatComboBoxActionPerformed
        // TODO add your handling code here:
        String data = "";
        if (this.inputFormatComboBox.getSelectedIndex() != -1) {
            this.inputFormat = (String)this.inputFormatComboBox.getItemAt(this.inputFormatComboBox.getSelectedIndex());
            java.awt.CardLayout cardLayout = (java.awt.CardLayout)(inputMainPanel1.getLayout());
            cardLayout.show(inputMainPanel1, this.inputFormat);
        }
        statusLabel.setText("Input Format set to " + this.inputFormat);
    }//GEN-LAST:event_inputFormatComboBoxActionPerformed

    private void gsiInButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gsiInButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gsiInButton1ActionPerformed

    private void stationIndicatorTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stationIndicatorTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stationIndicatorTextField1ActionPerformed

    private void gsiOutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gsiOutButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gsiOutButton1ActionPerformed

    private void stationIndicatorOutTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stationIndicatorOutTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stationIndicatorOutTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TricotUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TricotUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TricotUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TricotUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TricotUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane configTabbedPane;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton convertButton;
    private javax.swing.JPanel csvInputPanel1;
    private javax.swing.JPanel csvOutputPanel1;
    private javax.swing.JButton gsiInButton1;
    private javax.swing.JPanel gsiInputPanel1;
    private javax.swing.JTextField gsiInputTextField1;
    private javax.swing.JButton gsiOutButton1;
    private javax.swing.JPanel gsiOutputPanel1;
    private javax.swing.JTextField gsiOutputTextField1;
    private javax.swing.JPanel inputConfigPanel;
    private javax.swing.JComboBox<String> inputFormatComboBox;
    private javax.swing.JPanel inputMainPanel1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel outputConfigPanel;
    private javax.swing.JComboBox<String> outputFormatComboBox;
    private javax.swing.JPanel outputMainPanel1;
    private javax.swing.JPanel rmgInputPanel1;
    private javax.swing.JPanel rmgOutputPanel1;
    private javax.swing.JTextField siteIndicatorOutTextField1;
    private javax.swing.JTextField siteIndicatorTextField1;
    private javax.swing.JTextField stationIndicatorOutTextField1;
    private javax.swing.JTextField stationIndicatorTextField1;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
